name: glassmorphismcard
description: create a card have glassmorphism style.
version: 0.0.5
homepage: https://github.com/TranLinh101h/glassmorphism_card.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

